apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-pod-patch
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-pod-patch-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: argo-pod-patch
  apiGroup: rbac.authorization.k8s.io
