apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: multi-step-
spec:
  entrypoint: multi-step
  templates:
  - name: multi-step
    steps:
    - - name: step1
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "Step 1: Preparing data"
    - - name: step2
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "Step 2: Processing data"
    - - name: step3
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "Step 3: Finalizing results"

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo '{{inputs.parameters.message}}' && sleep 5"]
